### ISSUE TITLE
Encountering "GodotAndroidAdmobPlugin singleton not found!" Error

### ISSUE THREAD

**Issue by Shay-M** [cengiz-pz/godot-android-admob-plugin#1]
Hello, I'm trying to run the attached demo.
I installed according to the instructions

- I Change Install Folder button and select your project's addons directory
- uncheck Ignore asset root checkbox
- enable the plugin via the Plugins tab of Project->Project Settings... menu, in the Godot Editor

But I encountered the error messages:
```
  GodotAndroidAdmobPlugin plugin not initialized
  GodotAndroidAdmobPlugin singleton not found!
  GodotAndroidAdmobPlugin plugin not initialized
  GodotAndroidAdmobPlugin plugin not initialized
  GodotAndroidAdmobPlugin plugin not initialized
  GodotAndroidAdmobPlugin plugin not initialized
  GodotAndroidAdmobPlugin plugin not initialized
  GodotAndroidAdmobPlugin singleton not found!

```

**Additional Information:**
Godot Engine version: 4.2.1
Operating System: Windows 10

**Screenshots**
![singleton not found!](https://github.com/cengiz-pz/godot-android-admob-plugin/assets/22634623/353469c6-1cd3-44e2-9104-a3c1db70bc2f)

**Comment by cengiz-pz** [comment]
Hi @Shay-M, there are a couple of things to note here.  The most important is that the plugin will not work if you run it on Windows; you'll need to [export to and run on an Android](https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html) device.

The other issue is that the application's unique ID needs to be registered with AdMob for the ads to work & the demo app's ID is not.  The demo app's purpose is to provide a code sample for the time being.

**Comment by Shay-M** [comment]
I understand, thank you very much.
It runs with error message number 3 - of public static final int ERROR_CODE_NO_FILL
The ad request was successful, but no ad was returned due to lack of ad inventory.

But I guess it has to do with the settings of my Google Ads account

**Comment by cengiz-pz** [comment]
> It runs with error message number 3 - of public static final int ERROR_CODE_NO_FILL

Indeed, that error means that a suitable ad could not be found for the device location.  You may want to start off with [test ads.](https://developers.google.com/admob/android/test-ads)

**Comment by Shay-M** [comment]
Yes, I tried the test ads, and it still gives me these error messages.

P.S. In my work environment I added this line:
org.gradle.java.home=C:\\Users\\shay\\.jdks\\openjdk-19.0.2
to the gradle.properties file

**Comment by cengiz-pz** [comment]
Hi @Shay-M, were you able to fix your environment issues?

**Comment by Shay-M** [comment]
@cengiz-pz Sorry for the slow reply
Yes it runs it when I added the line:
org.gradle.java.home=C:\Users\shay\.jdks\openjdk-19.0.2

and use the Admob Plugin  update

**Comment by marufwayne00** [comment]
@Shay-M hi Brother , can i get your admob demo file ,please . i am also having same issue
