### ISSUE TITLE
Android 13 introduces changes to advertising ID

### ISSUE THREAD

**Issue by Shay-M** [cengiz-pz/godot-android-admob-plugin#10]
Hello, I wanted to ask, There is now an update from Google asking to declare whether there is use of AD_ID.

"If you say that your app uses advertising ID, we will block releases that don't include the com.google.android.gms.permission.AD_ID permission in the manifest file when targeting Android 13. When we block these releases, we will remind you to add the permission. If your release doesn't need advertising ID, you'll be able to skip the error and release. You can also update the declaration to turn off advertising ID release errors."

"When you answer this question, make sure to verify if any third-party SDK code in your app uses advertising ID. If so, you must declare that your app uses it. Some SDKs, such as the Google Mobile Ads SDK (Play Services ads) may already declare the com.google.android.gms.permission.AD_ID permission in the SDK's library manifest. If your app uses these SDKs as dependencies, the com.google.android.gms.permission.AD_ID permission from the SDK's library manifest will be merged with your app's main manifest by default, even if you don't explicitly declare the permission in your app's main manifest."

So I guess there is a use, if I'm not mistaken?

**Comment by cengiz-pz** [comment]
@Shay-M, yes, Ads SDK handles the advertizing ID behind the scenes.

**Comment by Shay-M** [comment]
@cengiz-pz Ok thank you!
