### ISSUE TITLE
AdSize: Fluid returning wrong banner dimensions

### ISSUE THREAD

**Issue by syntaxerror247** [cengiz-pz/godot-android-admob-plugin#15]
I am using function get_banner_dimension_in_pixel().height but it is returning -1

And why you removed adaptive_banner in this new release?

**Comment by cengiz-pz** [comment]
> why you removed adaptive_banner in this new release?

ADAPTIVE size was removed in order to achieve feature parity with the iOS version of the plugin and because the SDK has deprecated SMART_BANNER: https://developers.google.com/android/reference/com/google/android/gms/ads/AdSize#field-summary

**Comment by syntaxerror247** [comment]
@cengiz-pz according to docs fluid should match its parents width but it just leaves black empty area on both sides.
![IMG_20240821_161218.jpg](https://github.com/user-attachments/assets/295dc2e8-920a-4aee-a740-4905e6fa6ea2)



> get_banner_dimension_in_pixel().height but it is returning -1

And any idea about this issue??

**Comment by cengiz-pz** [comment]
> according to docs fluid should match its parents width but it just leaves black empty area on both sides.

Yes, I have noticed that, but haven't yet had time to dig into it.

> get_banner_dimension_in_pixel().height but it is returning -1

Will also look into this one when I have some time.

**Comment by syntaxerror247** [comment]
Any update on this ??

**Comment by cengiz-pz** [comment]
> Any update on this ??

I have been mostly working on my apps during the last few weeks.  Didn't have enough time for the plugins.

**Comment by cengiz-pz** [comment]
> I am using function get_banner_dimension_in_pixel().height but it is returning -1

@syntaxerror247, I am not able to reproduce this.  Are you still getting -1 height for FLUID banners with the latest version of the plugin?

**Comment by cengiz-pz** [comment]
Wait.  I got -1 for width and height after reloading the banner at a different position (bottom).

**Comment by syntaxerror247** [comment]
Just tested it with v3.1 and I can reproduce it even with default top position

![IMG-20241114-WA0001](https://github.com/user-attachments/assets/b47fc33f-c66a-49da-ae11-3e7a987445a5)

**Comment by cengiz-pz** [comment]
From Google's AdMob code:

```
public final class AdSize {
   ...
    public boolean isAutoHeight() {
        return this.height == -2;
    }

    public boolean isFluid() {
        return this.width == -3 && this.height == -4;
    }

    public boolean isFullWidth() {
        return this.width == -1;
    }
    ...
}
```

These values are hardcoded.  I haven't yet found a way to get or calculate the actual size.

**Comment by cengiz-pz** [comment]
From Google [documentation for Adsize](https://developers.google.com/android/reference/com/google/android/gms/ads/AdSize#public-int-getheightinpixels-context-context):

```
public int getHeightInPixels ([Context](https://developer.android.com/reference/android/content/Context.html) context)
Returns the height of this [AdSize](https://developers.google.com/android/reference/com/google/android/gms/ads/AdSize) in physical pixels. For fluid size, it returns -1.

public int getWidthInPixels ([Context](https://developer.android.com/reference/android/content/Context.html) context)
Returns the width of this [AdSize](https://developers.google.com/android/reference/com/google/android/gms/ads/AdSize) in physical pixels. For fluid size, it returns -1.
```

`AdSize` was designed to return (-1, -1) size for FLUID ads.

**Comment by syntaxerror247** [comment]
I don't understand what the AdMob team was thinking when hardcoding these values 🫤. 
Thank you for your help! I'll try creating a method to calculate the dimensions manually and open a PR if I succeed.

**Comment by cengiz-pz** [comment]
By the way, I have noticed that AdSize.FULL_BANNER seems to do a better job of filling the screen width than FLUID.  Additionally, `get...InPixels()` methods return the actual size when FULL_BANNER is used.

**Comment by syntaxerror247** [comment]
@cengiz-pz Yes, `FULL_BANNER` performs better overall, but it's inconsistent. Sometimes, it ends up looking like this:
![IMG-20241115-WA0001](https://github.com/user-attachments/assets/20b33274-b6dc-4dbf-825b-647a35c63ec6)

For now, I'm sticking with BANNER. It doesn't fill the width, but at least it avoids the black bars on both sides.
