### ISSUE TITLE
AdmobPlugin singleton not found!

### ISSUE THREAD

**Issue by kljoi** [cengiz-pz/godot-android-admob-plugin#18]
in Godot 4.3, when i add the Admob node to the scene i get an error saying : AdmobPlugin singleton not found!
i already activated the plugin and reloaded the project

**Comment by syntaxerror247** [comment]
@kljoi Are you testing it on android? 
This plugin will only work on android  devices.

**Comment by ckidwell** [comment]
Came here to report/search on the same error.

I'm a little confused about the expectations, so here's what happens:

1) Add admob node to scene (must be done in editor)
2) Press play in editor 
3) receive error `AdmobPlugin singleton not found!`

I don't have any errors in my project before adding this AdMob node - is there something you can do to check if your in editor and not throw the error? 

I get you are saying this singleton only works while on an Android device - but why throw errors in the editor instead of preventing them?

**Comment by syntaxerror247** [comment]
Well @ckidwell these errors just serves as warnings. And don't have any real effects.

And yes these errors can be suppressed with some minor changes.
@cengiz-pz if you want I can create a PR for that.

**Comment by kljoi** [comment]
I'm a little late for this but, for me, the plugin didn't work when i tried it on android device.  so i thought the error `AdmobPlugin singleton not found!` was the issue which is why i reported it, i ended up using the other Admob plugin from the **poingstudios** it also didn't work at first, but later on i figured out that the issue might have been because of two reasons:

1. i was using my own app ID with some test unit IDs that i got from a video tutorial.
2. After i installed the plugin (this plugin or the other one by poingstudios) , i was getting an error when exporting, so maybe the SDK version wasn't compatible, so i installed another version.

However, now that you have mentioned the error is just a warning, i will be trying it again, because i found that working with this plugin was actually easier than the one by poingstudios

**Comment by ckidwell** [comment]
@syntaxerror247   if the error in the editor has no effect/purpose in the editor I would be of the opinion it leads people to think there is something wrong that needs fixing - makes sense to me to suppress it there?

Then again - I'm just one set of feedback.  If you want to wait for more feedback on this before making a code change I have no issue with that.

**Comment by cengiz-pz** [comment]
> if you want I can create a PR for that.

Hi @syntaxerror247, what kind of a solution did you have in mind?

**Comment by syntaxerror247** [comment]
@cengiz-pz I was thinking about adding a condition before printing errors.
E.g. 
```
func initialize() -> void:
	if _plugin_singleton == null:
		if not OS.has_feature("editor"): printerr("%s plugin not initialized" % PLUGIN_SINGLETON_NAME)
```

**Comment by cengiz-pz** [comment]
@syntaxerror247, I was thinking of `OS.get_name()`, but your solution is better.

**Comment by cengiz-pz** [comment]
@syntaxerror247, will it work if the editor is running on Android?

**Comment by syntaxerror247** [comment]
@cengiz-pz It should. Because Android editor will also have editor feature. Here we are not specifying any OS. So technically it should work in web too.

**Comment by cengiz-pz** [comment]
@syntaxerror247, I never tried the Android UI.  I am just wondering if you run your app on Android via the Godot Editor Android UI, whether that error message would get displayed at all (even when actually needed.)  In other words, would `OS.has_feature("editor")` return `true` when you're running the app.

**Comment by syntaxerror247** [comment]
> would OS.has_feature(\"editor\") return true when you're running the app.

When it will run inside godot android editor UI, Yes it will return true.

But it will return false in exported apk

**Comment by cengiz-pz** [comment]
Yes, I have read the following.

https://docs.godotengine.org/en/stable/tutorials/export/feature_tags.html

& I think we should be ok with your solution, because we have to build using the export template in order to use the plugin anyway.  When a template build is used, then `OS.has_feature("editor")` will return `false`.

**Comment by syntaxerror247** [comment]
@cengiz-pz it would be better to update this in other plugins too. Because as @ckidwell mentioned it error lead to confusion that something is wrong.
