### ISSUE TITLE
Game crashes on startup on Android when plugin is installed. Godot 4.3

### ISSUE THREAD

**Issue by ZachBeauchamp** [cengiz-pz/godot-android-admob-plugin#19]
Unsure why this happens. Only clue I have is this error I get when I make an android build. 
![image](https://github.com/user-attachments/assets/f046e8f6-bf16-498c-882d-8289945cc314)

**Comment by syntaxerror247** [comment]
@ZachBeauchamp make sure that the scene that contains the Admob node is selected and opened in Editor when exporting for Android.

**Comment by ZachBeauchamp** [comment]
I tried this. Seems to have made some progress. But now i've got this error. Which seems to also be resulting in a crash on startup. 
![image](https://github.com/user-attachments/assets/ccbe6cd7-8040-4591-9b67-650579416b9c)

**Comment by syntaxerror247** [comment]
@ZachBeauchamp this error is only a problem if you are getting this on android, which doesn't seems the case here. You can ignore this. Either way it will not crash the game I guess.

And I think there should be some other reasons behind crash. Try using logcat, to see what error you are getting. https://github.com/cengiz-pz/godot-android-admob-plugin/blob/main/README.md#adb-logcat

**Comment by cengiz-pz** [comment]
Looks like this issue was auto-closed by my comment in PR 20.  Reopening

**Comment by ZachBeauchamp** [comment]
I have figured out the issue! I just did not set it on my main scene.

**Comment by cengiz-pz** [comment]
@ZachBeauchamp, what did you not set?  You didn't add an Admob node to your main scene or set the App ID on the node?

**Comment by ZachBeauchamp** [comment]
I did not add admob to my main scene I had it in another scene. So it is not crashing now. I have followed this tutorial https://www.youtube.com/watch?v=V9_Gpy0R3RE however it seems admob is not initializing based on my debugging.
![image](https://github.com/user-attachments/assets/f7709ded-e6a7-48d8-bb2c-738fa263ed4d)
This is my script. I have my app ID setup, and I am using test ID for the rewarded ad.

**Comment by syntaxerror247** [comment]
@ZachBeauchamp it is not necessary to add Admob node to your main scene, you just need to keep the scene that contains the Admob node opened and selected in editor.

> it seems admob is not initializing based on my debugging

And for this issue, I can say from your screenshot that you haven't connected the signals from Admob node to your script.

- select admob node, go to signals tab in inspector
- connect `initialization_completed` and `rewarded_ad_user_earned_reward` signal to this script in your screenshot.

**Comment by ZachBeauchamp** [comment]
I have done this. But I see what you mean, the symbol for a properly connected signal is not there. It does not seem to be there for a few of my signals but they are all working. I think admob is just not initializing, not sure why.
![image](https://github.com/user-attachments/assets/6638ab0c-60a2-4949-95d8-a550ce6e4d95)

**Comment by ZachBeauchamp** [comment]
For example the pressed signal does not have the symbol. But it is working fine I made sure.

**Comment by syntaxerror247** [comment]
@ZachBeauchamp Can you send the pic of your scene tree containing Admob node and also indicate above script is attached to which node

**Comment by ZachBeauchamp** [comment]
![image](https://github.com/user-attachments/assets/f6df69f2-4d3d-4a22-af7f-bea58e44fdc8)
Sure! The selected rewadedAdButton is the one the signals are attached to.

**Comment by syntaxerror247** [comment]
OK, that looks good. Did you tried using logcat

**Comment by ZachBeauchamp** [comment]
I have not, I will google it now!

**Comment by ZachBeauchamp** [comment]
Is this something I will use on my phone? Like an app from the app store?

**Comment by syntaxerror247** [comment]
you need platform tools(its a small zip containing adb.exe) and need to enable usb debugging on your device

**Comment by ZachBeauchamp** [comment]
![image](https://github.com/user-attachments/assets/96fe2a95-37ff-4746-8977-465c8b96dc47)
And you said before that seeing these errors in engine are nothing to worry about?

**Comment by syntaxerror247** [comment]
Yes, these errors in editor is expected and will be suppressed in next update🙂. You don't need to worry about that just try logcat.

**Comment by ZachBeauchamp** [comment]
![image](https://github.com/user-attachments/assets/d22dbebb-ede7-4305-a461-bfa60d3796df)
I see this in the docs. I must run the app in debug mode for debug ads to load. I am making a build of the game and downloading it on my phone. How would I run it in debug mode? Unsure if thats even it tho since its not initializing.

**Comment by syntaxerror247** [comment]
@ZachBeauchamp yeah I think this could be the main issue. During export, make sure export_with_debug is checked. 

![Screenshot 2024-09-26 233855](https://github.com/user-attachments/assets/a2bb9557-f3ed-4c1f-8ebd-e1013ba2acb7)

**Comment by ZachBeauchamp** [comment]
Oh I got it to work! I just called initialize on my root node rather then a child!

**Comment by syntaxerror247** [comment]
@ZachBeauchamp can you please explain how to solved it

**Comment by ZachBeauchamp** [comment]
Yeah, I moved all the code for calling the admob, initializing and the signals, to the root node of my main scene, rather then a child node of it.

**Comment by syntaxerror247** [comment]
If it was solved due to this then, it must be that your signals were not connected properly.
Well, atleast now your issue is solved.

**Comment by ZachBeauchamp** [comment]
Indeed. Altho I am not sure how I can use ads on any scene that is not my main scene? For example I would like to have an ad button to double coins on my end game screen scene.

**Comment by syntaxerror247** [comment]
create a global script and reference admob node in that script. This way you will be able to use it in any scene through global script. 
For more detailed info i would recommend to create a topic in official godot forum or its discord server. You will surely get help there.

**Comment by ZachBeauchamp** [comment]
Sure thank you!

**Comment by marywillowson** [comment]
Hello, I'm experiencing the same issue as Zach, but on Godot 4.4 stable. With the plugin turned on, my game crashes immediately after launch. As far as I understand moving the Admob node to the main scene fixed it for Zach, but for me it didn't help. This is my scene tree with the node:

![Image](https://github.com/user-attachments/assets/b959a1a5-f13c-48c3-99af-57c09bd54f3f)

This scene is opened and selected when I export the game. I also used logcat as advised in this thread and I'm getting these three errors whenever I try running the game on my phone:

03-11 14:01:28.378 23657 23657 E AndroidRuntime: Process: math.flight, PID: 23657
03-11 14:01:28.381  1639  2423 E ActivityManager: stark error packagemath.flight
03-11 14:01:28.399  1639 23675 E ActivityManager: stark EPkgAVer.get(package) = math.flight

Anybody knows how to fix this? Thanks!
