### ISSUE TITLE
Link to Godot's "create custom Android build" tutorial is no longer valid

### ISSUE THREAD

**Issue by Quadragintillion** [cengiz-pz/godot-android-admob-plugin#2]
I'm not entirely sure what the contents of the original link were, but I believe [this](https://docs.godotengine.org/en/stable/tutorials/export/android_gradle_build.html) is the new page.

**Comment by cengiz-pz** [comment]
@Quadragintillion, yes it looks like the doc has moved for Godot 4.2.  I'll update the docs.  Thanks for reporting the problem & using the plugin!
