### ISSUE TITLE
Failing to initialize and failing to load an ad

### ISSUE THREAD

**Issue by TheSkyOne** [cengiz-pz/godot-android-admob-plugin#22]
I have this little snippet of code for testing
```
admob.initialize()
await admob.initialization_completed
admob.load_image_interstitial_ad()
print("loaded: %s" %admob.is_interstitial_ad_loaded())
await admob.interstitial_ad_loaded
print("loaded: %s" %admob.is_interstitial_ad_loaded())
```
when `_on_initialization_completed` is called I print the received `status_data` and this is what I get
`{ "com.google.android.gms.ads.MobileAds": { "initializationState": <null>, "latency": 10016, "description": "Timeout." } }` which doesnt seem correct that initializationState is null
the following issue I am presuming is as a result of the failed initialization but I'll include it anyways
I am getting ad failed to load and in `_on_interstitial_ad_failed_to_load` I am printing the error data and this is the result
`
{ "response_info": "{\n  \"Response ID\": \"null\",\n  \"Mediation Adapter Class Name\": \"\",\n  \"Adapter Responses\": [],\n  \"Response Extras\": {}\n}", "code": 0, "domain": "com.google.android.gms.ads", "cause": {  }, "message": "Unable to obtain a JavascriptEngine." }
`
help would be much appreciated!

**Comment by syntaxerror247** [comment]
> Unable to obtain a JavascriptEngine

It seems like you are using an adblocker. Check your DNS setting too.

**Comment by TheSkyOne** [comment]
what do you mean im using an adblocker? I am simply running the app through remote debug
and please give more details about my DNS settings, what about them would be bad? what should I expect to see or not see?

**Comment by syntaxerror247** [comment]
@TheSkyOne this error `Unable to obtain a JavascriptEngine` occurs when you are using an adblocker in your device. And i was asking if you are using a private dns provider to block ads. But it does not seems to be the case.
This error also occurs due to internet connection (I am assuming you are connected to internet).

Have you enabled `Internet` permission in Android Export ?

**Comment by TheSkyOne** [comment]
that was the issue! I was using a private DNS provider, I set it up very long ago but when you mentioned it I remembered.
I guess `initializationState` being null had nothing to do with it (as it still shows null even though its working now)
Thank you! 🙂
