### ISSUE TITLE
Error when dismissing consent form

### ISSUE THREAD

**Issue by jcarnaxide** [cengiz-pz/godot-android-admob-plugin#24]
Hello Cengiz,

I am having some trouble when running your Admob plugin, and making use of the consent API. I believe the consent is being set properly, but I am seeing some sort of [error stack in logcat](https://gist.github.com/jcarnaxide/34c067610a0ae667230f3ac7253e8223).

It appears that it is possible for a null value to be passed to your [consent form dismissed handler code](https://github.com/cengiz-pz/godot-android-admob-plugin/blob/main/admob/src/main/java/org/godotengine/plugin/android/admob/AdmobPlugin.java#L749)

It is totally possible I am just doing something wrong here, Maybe some of the logs I shared will show that. There is a log line that mentions seting the callback to null, I am not sure this is normal.

Maybe this error could just be ignored? Or maybe we can expect formError to comeback null sometimes, if so, we could add some null checks [here](https://github.com/cengiz-pz/godot-android-admob-plugin/blob/main/admob/src/main/java/org/godotengine/plugin/android/admob/AdmobPlugin.java#L848-L855) in your convert function.

**Comment by krebszattila** [comment]
I have the same problem. It doesn't matter if I click on the "Consent" or on the "Do not consent" button in the form, the NullPointerException occours always. Because of this the `consent_form_dismissed` signal is not emitted.
