### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by zt-pawer** [cengiz-pz/godot-android-admob-plugin#25]
The documentation may need some fixes:

- AssetLib instructions suggest to search for Admob plugin, but that is related to another github project from Poing Studio

![image](https://github.com/user-attachments/assets/6ebe72ae-5dba-4235-9551-79a46bea4c78)

- Releases have this note _This plugin has been tested against and supports Godot version 4.3._ Does it mean that is backward compatible to 4.2.1 and in general 4.x (I understand that has not been tested, but is it compatible?)

**Comment by cengiz-pz** [comment]
Hi @zt-pawer, the plugin will not appear in the search results for Godot versions 4.2 and below.  This is because I have set the minimum supported Godot version to 4.3 as the plugin hasn't been tested with other versions.

**Comment by cengiz-pz** [comment]
>  Does it mean that is backward compatible to 4.2.1 and in general 4.x (I understand that has not been tested, but is it compatible?

I can't confirm compatibility with version prior to 4.3 for the latest version of the plugin.  Please check previous releases to see which plugin release is compatible with which Godot version.

**Comment by zt-pawer** [comment]
> > Does it mean that is backward compatible to 4.2.1 and in general 4.x (I understand that has not been tested, but is it compatible?
> 
> I can't confirm compatibility with version prior to 4.3 for the latest version of the plugin. Please check previous releases to see which plugin release is compatible with which Godot version.

I will be happy to create the releases for 4.2.1 to be added to this repo, do you have a process that I can follow to do that?

**Comment by syntaxerror247** [comment]
I had asked about `backward capability` for plugin in contributors chat and Android maintainer had told me that v2 plugin will work with 4.2+. I also tried my plugin build with 4.3 dependency and it really worked with v4.2.2 but one user told me that it crashed on older version and he was only able to use it on 4.3.

**Comment by cengiz-pz** [comment]
> I will be happy to create the releases for 4.2.1 to be added to this repo, do you have a process that I can follow to do that?

The missing part is not creating the releases, but rather testing if the existing releases are backward compatible.

By the way, if you're looking for Godot 4.2.1 support, then you may want to look into [plugin version 1.0](https://github.com/cengiz-pz/godot-android-admob-plugin/releases/tag/v1.0).
