### ISSUE TITLE
AdmobPlugin singleton not found!   

### ISSUE THREAD

**Issue by methbaba** [cengiz-pz/godot-android-admob-plugin#36]
:: error  because of which we cannot initialize

ad_test_script :: 
![Screenshot 2024-12-23 122922](https://github.com/user-attachments/assets/ce4c0847-05e4-4f34-88e2-fbe7118e3e4d)

extends Node2D

@onready var admob: Admob = $Admob

var is_intialized:bool=false
func _ready() -> void:
	admob.initialize()

func _on_touch_screen_button_pressed() -> void:
	print("pressed")
	if is_intialized:
		admob.load_rewarded_ad()
		await admob.rewarded_ad_loaded
		admob.show_rewarded_ad()
	

func _on_admob_initialization_completed(status_data: InitializationStatus) -> void:
	is_intialized=true

I am using godot 4.3

**Comment by syntaxerror247** [comment]
Duplicate of https://github.com/cengiz-pz/godot-android-admob-plugin/issues/18

**Comment by methbaba** [comment]
I see thanks for help  , I ran on android and the plugin works fine
