### ISSUE TITLE
Banner size not found, version 2.0

### ISSUE THREAD

**Issue by JeanPhilippeDubois** [cengiz-pz/godot-android-admob-plugin#5]
On version 2.0, I would like to report this issue : 

![image](https://github.com/cengiz-pz/godot-android-admob-plugin/assets/44825459/5f911312-7cf8-4541-8dbf-363d5ead5e08)

I have tried to set the size and different combinations of the plugin settings to do it, I've also looked at the code and just ended up passing the parameter manually but there seems to be a problem there.

I've installed the plugin as it should be, no need to rush on the fix as I said, I've fixed it myself.

**Comment by cengiz-pz** [comment]
Hi @JeanPhilippeDubois, @feersow, I have updated the 2.0 release (same link) with a fix.  Please update your plugins and let me know of your issues are resolved.

**Comment by JeanPhilippeDubois** [comment]
@cengiz-pz I would confirm that the fix works, thank you for the quick work, just had to test it out, thanks very much,
