### ISSUE TITLE
Handling Load Errors

### ISSUE THREAD

**Issue by DanielBitencourt** [cengiz-pz/godot-android-admob-plugin#9]
Hi,

When i use "error_data.get_code()", it return code "0".
After tuning phone to "Airplane Mode" it return code "0".
After disabling internet on phone it return code "0". Wouldn't it be correct to return code "2" due to a network error?

I'm trying to block the use of the app when disconnected from the internet, so the user can only use it with ads.
What is the best way to check the internet connection for ads?

**Comment by cengiz-pz** [comment]
Hi @DanielBitencourt, the plugin is returning the error code that Admobs API returns:

> https://github.com/cengiz-pz/godot-android-admob-plugin/blob/02064004daa9b1e61ddf5452cda95d0eaa9a70b4/admob/src/main/java/org/godotengine/plugin/android/admob/AdmobPlugin.java#L806

If you find that the error code returned by the API is unreliable, then you may want to try the following plugin to get the connection state from the Android OS:

> https://github.com/MeroVinggen/Godot-AndroidInternetConnectionStatePlugin

**Comment by DanielBitencourt** [comment]
> Hi @DanielBitencourt, the plugin is returning the error code that Admobs API returns:
> 
> > https://github.com/cengiz-pz/godot-android-admob-plugin/blob/02064004daa9b1e61ddf5452cda95d0eaa9a70b4/admob/src/main/java/org/godotengine/plugin/android/admob/AdmobPlugin.java#L806
> 
> If you find that the error code returned by the API is unreliable, then you may want to try the following plugin to get the connection state from the Android OS:
> 
> > https://github.com/MeroVinggen/Godot-AndroidInternetConnectionStatePlugin

yeah I found this plugin.
After research I found that the best way to check the connection is through admob with codes "0" and "2".
Thanks man!!
